apps/cadmin/urls.py
from django.urls import path
from .views import *

app_name = 'cadmin'

urlpatterns = [
    path('', index, name='index'),
    path('logout/', logout_user, name='logout_user'),
    path('login/', login_user, name='login'),
    # company
    path('company-add',
         company_add, name='company_add'),
    path('company-edit/<int:pk>/', company_edit, name='company_edit'),

    # users
    path('company/<int:pk>/', company_home, name='home'),
    path('company/<int:pk>/account-add',
         company_user_add, name='company_user_add'),
    path('company/<int:company_pk>/account-edit/<int:pk>',
         company_user_edit, name='company_user_edit'),
    path('company/<int:company_pk>/change-password/<int:pk>',
         change_password_user, name='company_user_change_password'),
    path('company/<int:company_pk>/set-avatar/<int:pk>',
         set_user_avatar, name='set_avatar'),

    # sites
    path('company/<int:pk>/sites/',
         company_sites, name='company_sites'),
    path('company/<int:pk>/site-add/',
         company_site_add, name='company_site_add'),
    path('company/<int:company_pk>/site-edit/<int:pk>/',
         company_site_edit, name='company_site_edit'),

    # divisons
    path('company/<int:pk>/divisons/',
         company_divisions, name='company_divisions'),
    path('company/<int:pk>/divison-add/',
         company_division_add, name='company_division_add'),
    path('company/<int:company_pk>/divison-edit/<int:pk>/',
         company_divison_edit, name='company_divison_edit'),

    # commodities
    path('company/<int:pk>/commodities/',
         company_commodities, name='company_commodities'),
    path('company/<int:pk>/commodity-add/',
         company_commodity_add, name='company_commodity_add'),
    path('company/<int:company_pk>/commodity-edit/<int:pk>/',
         company_commodity_edit, name='company_commodity_edit'),

    # meters
    path('company/<int:pk>/meters/',
         company_meters, name='company_meters'),
    path('company/<int:pk>/meter-add/',
         company_meters_add, name='company_meter_add'),
    path('company/<int:company_pk>/meter-edit/<int:pk>/',
         company_meter_edit, name='company_meter_edit'),

    # fetch commodities
    path('company/<int:pk>/fetch_commodities/',
         commodity_fetch, name='fetch_commodities'),

    path('company/<int:pk>/master_upload/',
         master_upload, name='master_upload'),
    path('company/<int:pk>/custom_field/',
         custom_field_upload, name='custom_field'),

    # custom fields
    path('company/<int:pk>/custom-fields/',
         company_custom_fields, name='custom_fields'
         ),
    path('company/<int:pk>/custom-field-add/',
         company_custom_field_add, name='custom_field_add'),

    path('company/<int:pk>/consumtion_data/',
         consumtion_data_upload,
         name='consumtion_data_upload')

]

config/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi


schema_view = get_schema_view(
    openapi.Info(
        title="Enkumo API",
        default_version='v1',
        description="Enkumo Rest APIs",
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)
urlpatterns = [
    path('docs', schema_view.with_ui(
        'swagger',
        cache_timeout=0
    ), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui(
        'redoc',
        cache_timeout=0
    ), name='schema-redoc'),
    path(r'admin/', admin.site.urls),
    # Modules
    path('api/', include('apps.api.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('cadmin/', include('apps.cadmin.urls'))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/cadmin/models.py
from django.db import models

# Create your models here.

apps/data/models.py
from __future__ import unicode_literals

import os
from datetime import datetime

from django.db import models, transaction

from apps.commons.models import BaseModel
from apps.data.utils.file.read import upload_meter_data
from apps.sites.models import Site


class Commodity(BaseModel):
    name = models.CharField(max_length=100)
    is_active = models.BooleanField(default=True)
    site = models.ForeignKey(Site, related_name='commodities',
                             on_delete=models.DO_NOTHING, null=True)
    company = models.ForeignKey(
        'company.Company', null=True, blank=True,
        on_delete=models.CASCADE, related_name='commodities')

    class Meta:
        verbose_name_plural = 'Commodities'

    def __str__(self):
        return str(self.name)


class MeterRecord(BaseModel):
    ATYPE_CHOICES = (
        ('actual', 'Actual'),
        ('forcasted', 'Forcasted'),
    )
    TYPE_CHOICES = (
        ('hh', 'HH'),
        ('hour', 'Hour'),
        ('daily', 'Daily'),
        ('weekly', 'Weekly'),
        ('monthly', 'Monthly'),
        ('yearly', 'Yearly'),
    )
    mtype = models.CharField(
        choices=TYPE_CHOICES, default='hh', max_length=100, null=True, blank=True)
    origin_type = models.CharField(
        choices=ATYPE_CHOICES, default='actual', max_length=100, null=True, blank=True)
    meter = models.ForeignKey('sites.Meter', on_delete=models.CASCADE)
    site = models.ForeignKey('sites.Site', on_delete=models.CASCADE, null=True,
                             blank=True)
    company = models.ForeignKey('company.Company', on_delete=models.CASCADE, null=True,
                                blank=True)
    value = models.FloatField(null=True, default=0)
    date = models.DateTimeField(default=None)

    def __str__(self):
        return str(self.meter.number)

    class Meta:
        verbose_name_plural = 'Meter Readings'


class MeterDataFile(BaseModel):
    site = models.ForeignKey('sites.Site', null=True,
                             on_delete=models.CASCADE)
    commodity = models.ForeignKey(
        'data.Commodity', null=True, on_delete=models.CASCADE)
    meter = models.ForeignKey('sites.Meter', null=True,
                              on_delete=models.CASCADE)
    file = models.FileField(upload_to="meter", blank=True, null=True)

    def save(self, *args, **kwargs):
        # if not self.pk:
        super(MeterDataFile, self).save(*args, **kwargs)
        self.process_file(self.file.file)

    @transaction.atomic
    def process_file(self, data_file):
        fileName, fileExtension = os.path.splitext(data_file.name)
        if (fileExtension.lower() == '.xlsx' or fileExtension.lower() == '.xls'):
            upload_meter_data(self.meter, data_file, self.commodity)

apps/cadmin/forms.py
import re
from django import forms
from django.contrib.auth import get_user_model, password_validation

from apps.commons.models import CustomField
from apps.company.models import Company, Devision, Profile
from apps.data.models import Commodity
from apps.sites.models import Meter, Site
from apps.company.constants import USER_ROLE_CHOICES

from django.utils.translation import gettext as _

PHONE_NUMBER_REGEX = re.compile(r"^(([+]?\d{3})-?)?\d{7,10}$")

User = get_user_model()


class ChangePasswordForm(forms.ModelForm):
    """
    form to change user password
    """
    password = forms.CharField(
        label='Password',
        widget=forms.PasswordInput(
            attrs={'class': 'form-control', 'placeholder': '', 'required': 'required'}),
        strip=False,
    )

    confirm_password = forms.CharField(
        label='Confirm Password',
        widget=forms.PasswordInput(
            attrs={'class': 'form-control', 'placeholder': '', 'required': 'required'}),
        strip=False,
    )

    class Meta:
        model = User
        fields = ['password', 'confirm_password']

    def clean_confirm_password(self):
        password = self.cleaned_data['password']
        confirm_password = self.cleaned_data['confirm_password']

        if password and confirm_password and password != confirm_password:
            raise forms.ValidationError('Password mismatch')
        password_validation.validate_password(password, self.instance)
        return password

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user


class UserRegisterForm(forms.ModelForm):
    """
    Form to register a new user
    """
    password = forms.CharField(
        label='Password',
        widget=forms.PasswordInput(
            attrs={'class': 'form-control', 'placeholder': '', 'required': 'required'}),
        strip=False,
    )

    confirm_password = forms.CharField(
        label='Confirm Password',
        widget=forms.PasswordInput(
            attrs={'class': 'form-control', 'placeholder': '', 'required': 'required'}),
        strip=False,
    )
    first_name = forms.CharField(label="First Name")
    last_name = forms.CharField(label="Last Name")
    email = forms.EmailField(label="Email Address")
    role = forms.ChoiceField(choices=USER_ROLE_CHOICES)
    site = forms.ModelChoiceField(queryset=Site.objects.all(),
                                  required=False)
    phone_number = forms.CharField(label='Phone Number', required=False)

    class Meta:
        model = User
        fields = [
            'first_name',
            'last_name',
            'email',
            'phone_number',
            'password',
            'confirm_password',
            'role',
            'site',
        ]
        widgets = {
            'email': forms.EmailInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': '',
                    'required': 'required',
                },
            ),
            'first_name': forms.EmailInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': '',
                    'required': 'required',
                },
            ),
            'last_name': forms.EmailInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': '',
                    'required': 'required',
                },
            ),

        }

    def clean_confirm_password(self):
        password = self.cleaned_data['password']
        confirm_password = self.cleaned_data['confirm_password']

        if password and confirm_password and password != confirm_password:
            raise forms.ValidationError('Password mismatch')
        password_validation.validate_password(password, self.instance)
        return password

    def clean_email(self):
        email = self.cleaned_data.get('email')
        user = User.objects.filter(email=email)
        if user.exists():
            raise forms.ValidationError("User with email already exists!")
        return email

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password"])
        email = self.cleaned_data['email']
        user.username = email
        user.is_active = True
        if commit:
            user.save()
        return user


class UserEditForm(forms.ModelForm):
    """
    Form to edit  new user
    """
    first_name = forms.CharField(label="First Name")
    last_name = forms.CharField(label="Last Name")

    class Meta:
        model = User
        fields = [
            'first_name',
            'last_name',
        ]


class ProfileForm(forms.ModelForm):

    class Meta:
        model = Profile
        fields = [
            'id',
            'user',
        ]
        labels = {
            "user": "User"
        }


class ProfileEditForm(forms.ModelForm):
    phone_number = forms.CharField(label="Phone Number", required=False)

    class Meta:
        model = Profile
        fields = [
            'phone_number',
            'role',
            'site',
        ]

    def clean_phone_number(self):
        number = self.cleaned_data.get('phone_number')
        self.validate_phone_number(number)
        return number

    @staticmethod
    def validate_phone_number(number):
        phone_number = str(number)

        if not PHONE_NUMBER_REGEX.match(phone_number):
            raise forms.ValidationError(
                _('Phone Number format is not valid. Some examples of supported'
                  ' phone numbers are numbers are 9811111111, 08256666,'
                  ' 977-9833333333, +977-9833333333, 977-08256666')
            )

        return number


class ProfileAvatarForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['avatar']


class SiteForm(forms.ModelForm):

    class Meta:
        model = Site
        exclude = ["company"]
        labels = {
            'dno': 'DNO'
        }


class SiteEditForm(forms.ModelForm):

    class Meta:
        model = Site
        exclude = ["company", "country"]
        labels = {
            'dno': 'DNO'
        }


class DivisonForm(forms.ModelForm):

    class Meta:
        model = Devision
        exclude = ["company"]


class CommodityForm(forms.ModelForm):

    class Meta:
        model = Commodity
        fields = "__all__"

    def clean(self):
        clean = super().clean()
        name = self.cleaned_data.get('name')
        site = self.cleaned_data.get('site')
        commodity = Commodity.objects.filter(site=site, name=name)
        if commodity.exists():
            self.add_error('name', 'Commodity with Site {} already exists'.
                           format(site.name))

        return clean


class CommodityEditForm(forms.ModelForm):
    class Meta:
        model = Commodity
        fields = ["is_active"]


class MeterForm(forms.ModelForm):

    class Meta:
        model = Meter
        fields = ["number", "commodity"]

    def clean(self):
        clean = super().clean()
        number = self.cleaned_data.get('number')
        commodity = self.cleaned_data.get('commodity')

        meter = Meter.objects.filter(
            number=number, commodity=commodity, commodity__site=commodity.site)

        if meter.exists():
            self.add_error('number', 'Meter {} on Site {} already exists'.
                           format(number, commodity.site.name))

        return clean


class MeterEditForm(forms.ModelForm):

    class Meta:
        model = Meter
        fields = ["number", "commodity"]


class CompanyForm(forms.ModelForm):

    class Meta:
        model = Company
        fields = "__all__"

        widgets = {
            'expiry_date': forms.DateInput(
                attrs={
                    'class': 'datepicker',
                    "type": "Date"
                }
            )
        }


class CustomFieldForm(forms.ModelForm):
    class Meta:
        model = CustomField
        fields = ['id', 'name', 'field_type', 'country']

apps/cadmin/views/customfield.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.contenttypes.models import ContentType
from django.db import transaction
from django.shortcuts import redirect, render

from apps.cadmin.forms import CustomFieldForm
from apps.commons.models import CustomField
from apps.company.models import Company
from apps.region.models import Country


@login_required
def company_custom_fields(request, pk):
    context = {}
    try:
        company = Company.objects.get(pk=pk)
    except Company.DoesNotExist:
        messages.info(request, "No company found")
        return redirect("cadmin:index")

    custom_fields = CustomField.objects.filter(company=company)

    context['pk'] = pk
    context['objects'] = custom_fields
    context['url'] = 'custom_field'
    context['company'] = company
    return render(request, 'cadmin/customfield/custom_fields.html', context)


@transaction.atomic
@login_required
def company_custom_field_add(request, pk):
    context = {}
    try:
        company = Company.objects.get(pk=pk)
    except Company.DoesNotExist:
        messages.info(request, "No company found")
        return redirect("cadmin:index")

    sites = company.site_set.all()
    form = CustomFieldForm(request.POST or None)
    countries = [site.country.name for site in sites]
    form.fields['country'].queryset = Country.objects.filter(
        name__in=countries)

    content_type = ContentType.objects.get(app_label='sites', model='site')

    if request.method == 'POST':
        if form.is_valid():
            instance = form.save(commit=False)
            instance.model = content_type
            instance.company = company
            instance.save()
            messages.success(request, 'Custom Field Added Successfully.')
            return redirect('cadmin:custom_fields', pk)

    context['pk'] = pk
    context['form'] = form
    context['url'] = 'custom_field'
    context['sites_'] = sites
    context['company'] = company

    return render(request, 'cadmin/customfield/custom_fields_add.html', context)

apps/cadmin/templates/cadmin/meters/meter_add.html
{% extends 'sidebar.html' %}
{% load crispy_forms_tags %}
{% block title %} Meter Create{% endblock %}
{% block links %}
<li class="breadcrumb-item"> <a href="{% url 'cadmin:company_meters' company.pk %}">Meters</a> </li>
<li class="breadcrumb-item active">Meter Create</li>
{% endblock links %}

{% block content %}
<div class="container-fluid">
	<div class="row">
		<div class="col-12">
			<div class="card shadow">
				<div class="card-body">
					<h5 class="card-title">Add Meter</h5>
					<hr>

					<div class="">
						<form method="POST">
							{% csrf_token %}

							<div class="form-row col-md-12">
									<div class="form-group col-md-12">
												{{form.number|as_crispy_field}}
									</div>
									<div class="form-group col-md-12">
										<div id="div_id_site" class="form-group">
												<label for="id_site" class=" requiredField">
														Site<span class="asteriskField">*</span>
												</label>
												<div class="">
												<select name="site" class="select form-control" required="" id="id_site">
											<option value="" selected="">---------</option>
											{% for site in sites_ %}
											<option value="{{site.pk}}">{{site.name}}</option>
											{% empty %}
											<option value="" selected="">---------</option>
											{% endfor %}
										</select>
												</div>
										</div>
									</div>
									<!-- <div class="form-group col-md-12"> -->
									<!--   <div id="div_id_commodity" class="form-group"> -->
									<!--       <label for="id_commodity" class=" requiredField"> -->
									<!--           Commodity<span class="asteriskField">*</span> -->
									<!--       </label> -->
									<!--       <div class=""> -->
									<!--         <select name="commodity" class="select form-control" required="" id="id_commodity"> -->
									<!--         <option value="" selected="">---------</option> -->
									<!--         </select> -->
									<!--       </div> -->
									<!--   </div> -->
									<!-- </div> -->
									<div class="form-group col-md-12">
												{{form.commodity|as_crispy_field}}
									</div>

							</div>
							<div class="form-group col-12">
									<button class="btn btn-outline-secondary" type="submit">Submit</button>
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
	{% endblock content %}
	{% block javascript %}
	<script>
		$(document).ready(function(){
			$("#id_commodity").empty()
		});
			$("select").select2({
				theme: 'bootstrap',
				dropdownAutoWidth: true,
				width: 'auto'
			});

$("#id_site").change(function(){
	var site_val = $(this).val()
	const uri = "/cadmin/company/" + site_val + "/fetch_commodities";
	$.get(uri, function(data, status){

		$("#id_commodity").empty();
		for(var i=0; i<data.result.length; i++){
			var name = data.result[i].name;
			var pk = data.result[i].pk;
			var option = "<option value="+ pk +">" + name+ "</option>";
				$("#id_commodity").append(option);
		}
  });


})


	</script>

	{% endblock javascript %}

apps/cadmin/templates/cadmin/meters/meter_edit.html
{% extends 'sidebar.html' %}
{% load crispy_forms_tags %}
{% block title %} Meter Edit{% endblock %}

{% block links %}
<li class="breadcrumb-item"> <a href="{% url 'cadmin:company_meters' company.pk %}">Meters</a> </li>
<li class="breadcrumb-item active">Meter Edit</li>
{% endblock links %}

{% block content %}
<div class="container-fluid">
	<div class="row">
		<div class="col-12">
			<div class="card shadow">
				<div class="card-body">
					<h5 class="card-title">Edit Meter {{meter.number}}</h5>
					<hr>

					<div class="">
						<form method="POST">
							{% csrf_token %}

							<div class="form-row col-md-12">
									<div class="form-group col-12">
												{{form.number|as_crispy_field}}
									</div>

									<div class="form-group col-12">
												{{form.commodity|as_crispy_field}}
									</div>
							</div>
							<div class="form-group col-12">
									<button class="btn btn-outline-secondary" type="submit">Submit</button>
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
	{% endblock content %}
	{% block javascript %}
	<script>
			$("select").select2({
				theme: 'bootstrap',
				dropdownAutoWidth: true,
				width: 'auto'
			});

	</script>

	{% endblock javascript %}

apps/cadmin/templates/cadmin/meters/meters.html
{% extends 'sidebar.html' %}
{% block title %} Meters {% endblock %}

{% block links %}
<li class="breadcrumb-item active">Meters</li>
{% endblock links %}

{% block content %}

<div class="container-fluid">
	<div class="row">
		<div class="col-12">

			<div class="card shadow">
				<div class="card-body">
					<div class="div-wrapper mb-3">
							<div class="row no-gutters">
								<div class="col-6">
									<h5 class="card-title">Meters</h5>
									</div>
									<div class="col-6">
										<a href="{% url 'cadmin:company_meter_add' pk %}" class="btn
											btn-outline-secondary pull-right">Create New</a>
									</div>
								</div>
							</div>
					<table class="table">
						<thead>
							<tr>
								<th scope="col">#</th>
								<th scope="col">Number</th>
								<th scope="col">Hh</th>
								<th scope="col">Site</th>
								<th scope="col">Commodity</th>
								<th scope="col">Actions</th>
							</tr>
						</thead>
						<tbody>
							{% for object in objects %}
							<tr>
								<th scope="row">{{forloop.counter}}</th>
								<td>{{object.number}}</td>
								<td>{{object.hh}}</td>
								<td>{{object.commodity.site}}</td>
								<td>{{object.commodity}}</td>
								<td>
									<a class="btn btn-outline-secondary" href="{% url 'cadmin:company_meter_edit' company.pk object.pk %}">Edit</a>
								</td>
							</tr>
							{% empty %}
							<tr>
								<td colspan="3">
							No meters yet
								</td>
							</tr>
							{% endfor %}
						</tbody>
					</table>

				</div>
			</div>
		</div>
	</div>
</div>
{% endblock content %}