apps/cadmin/urls.py
from django.urls import path
from .views import *

app_name = 'cadmin'

urlpatterns = [
    path('', index, name='index'),
    path('logout/', logout_user, name='logout_user'),
    path('login/', login_user, name='login'),
    # company
    path('company-add',
         company_add, name='company_add'),
    path('company-edit/<int:pk>/', company_edit, name='company_edit'),

    # users
    path('company/<int:pk>/', company_home, name='home'),
    path('company/<int:pk>/account-add',
         company_user_add, name='company_user_add'),
    path('company/<int:company_pk>/account-edit/<int:pk>',
         company_user_edit, name='company_user_edit'),
    path('company/<int:company_pk>/change-password/<int:pk>',
         change_password_user, name='company_user_change_password'),
    path('company/<int:company_pk>/set-avatar/<int:pk>',
         set_user_avatar, name='set_avatar'),

    # sites
    path('company/<int:pk>/sites/',
         company_sites, name='company_sites'),
    path('company/<int:pk>/site-add/',
         company_site_add, name='company_site_add'),
    path('company/<int:company_pk>/site-edit/<int:pk>/',
         company_site_edit, name='company_site_edit'),

    # divisons
    path('company/<int:pk>/divisons/',
         company_divisions, name='company_divisions'),
    path('company/<int:pk>/divison-add/',
         company_division_add, name='company_division_add'),
    path('company/<int:company_pk>/divison-edit/<int:pk>/',
         company_divison_edit, name='company_divison_edit'),

    # commodities
    path('company/<int:pk>/commodities/',
         company_commodities, name='company_commodities'),
    path('company/<int:pk>/commodity-add/',
         company_commodity_add, name='company_commodity_add'),
    path('company/<int:company_pk>/commodity-edit/<int:pk>/',
         company_commodity_edit, name='company_commodity_edit'),

    # meters
    path('company/<int:pk>/meters/',
         company_meters, name='company_meters'),
    path('company/<int:pk>/meter-add/',
         company_meters_add, name='company_meter_add'),
    path('company/<int:company_pk>/meter-edit/<int:pk>/',
         company_meter_edit, name='company_meter_edit'),

    # fetch commodities
    path('company/<int:pk>/fetch_commodities/',
         commodity_fetch, name='fetch_commodities'),

    path('company/<int:pk>/master_upload/',
         master_upload, name='master_upload'),
    path('company/<int:pk>/custom_field/',
         custom_field_upload, name='custom_field'),

    # custom fields
    path('company/<int:pk>/custom-fields/',
         company_custom_fields, name='custom_fields'
         ),
    path('company/<int:pk>/custom-field-add/',
         company_custom_field_add, name='custom_field_add'),

    path('company/<int:pk>/consumtion_data/',
         consumtion_data_upload,
         name='consumtion_data_upload')

]

config/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi


schema_view = get_schema_view(
    openapi.Info(
        title="Enkumo API",
        default_version='v1',
        description="Enkumo Rest APIs",
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)
urlpatterns = [
    path('docs', schema_view.with_ui(
        'swagger',
        cache_timeout=0
    ), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui(
        'redoc',
        cache_timeout=0
    ), name='schema-redoc'),
    path(r'admin/', admin.site.urls),
    # Modules
    path('api/', include('apps.api.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('cadmin/', include('apps.cadmin.urls'))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>{% block title %}Home {% endblock %} | Enkumo</title>
	<link rel="icon" href="{% static 'images/enkumo.svg' %}" type="image/gif" sizes="16x16">

<link rel="stylesheet" type="text/css" href="{% static 'bower_components/bootstrap/dist/css/bootstrap.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'bower_components/select2/dist/css/select2.min.css' %}">
<link rel="stylesheet" href="{% static  'bower_components/components-font-awesome/css/font-awesome.min.css' %}">
<link rel="stylesheet" href="{% static  'bower_components/select2/dist/css/select2.min.css' %}">
<link rel="stylesheet" href="{% static  'css/dashboard.css' %}">
<link rel="stylesheet" href="{% static  'css/style.css' %}">
</head>
<body>

<nav class="navbar navbar-dark navbar-expand-lg bg-dark" style="z-index:9999">
	<a class="navbar-brand" href="{% url 'cadmin:index' %}">
		<img src="{% static 'images/enkumo.svg' %}" class="img-responsive" height="30" alt="">
	</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
		<ul class='navbar-nav mr-auto'>
		</ul>
    <ul class="navbar-nav float-lg-right">
			<li class="nav-item">
				<a class="nav-link" href="#">
					<i class="fa fa-user"></i>
					{{request.user}}</a>
      </li>
			&nbsp;
			<li class="nav-item">
				<a class="nav-link" href="{% url 'cadmin:logout_user' %}">
					<i class="fa fa-sign-out"></i>
					Sign Out</a>
      </li>

    </ul>

  </div>
</nav>
				<div class="container-fluid mt-2">
					<div class="row">
						<div class="col-12">
							{% if messages %}
									{% for message in messages %}
											<div class="shadow alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
												<center>{{message}}</center>
												<button type="button" class="close" data-dismiss="alert" aria-label="Close">
													<span aria-hidden="true">&times;</span>
												</button>
											</div>
									{% endfor %}
							{% endif %}
						</div>
					</div>
				</div>
		{% block content %}
		{% endblock content %}
	
<script src="{% static 'bower_components/jquery/dist/jquery.min.js' %}"></script>
<script src="{% static 'bower_components/jquery-ui/jquery-ui.min.js' %}"></script>
<script src="{% static 'bower_components/bootstrap/dist/js/bootstrap.min.js' %}"></script>
<script src="{% static 'bower_components/select2/dist/js/select2.min.js' %}"></script>
<script>
	$(".alert").delay(3000).slideUp(1000, function() {
			$(this).alert('close');
	});
</body>
</html>

templates/sidebar.html
{% load static %}
{% load crispy_forms_tags %}

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="icon" href="{% static 'images/enkumo.svg' %}" type="image/gif" sizes="16x16">
	<title>{% block title %}Home {% endblock %} | Enkumo</title>

<link rel="stylesheet" type="text/css" href="{% static 'bower_components/bootstrap/dist/css/bootstrap.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'bower_components/select2/dist/css/select2.min.css' %}">
<link rel="stylesheet" href="{% static  'bower_components/components-font-awesome/css/font-awesome.min.css' %}">
<link rel="stylesheet" href="{% static  'bower_components/select2/dist/css/select2.min.css' %}">
<link rel="stylesheet" href="{% static  'css/dashboard.css' %}">

<link rel="stylesheet" href="{% static  'css/select2-bootstrap.min.css' %}" type="text/css">
<link rel="stylesheet" href="{% static  'css/style.css' %}">
{% block style %}
{% endblock style %}
</head>

<body>
<nav class="navbar navbar-dark navbar-expand-lg bg-dark fixed-top" style="z-index:9999">
	<a class="navbar-brand" href="{% url 'cadmin:index' %}">
		<img src="{% static 'images/enkumo.svg' %}" class="img-responsive"
																								height="30" alt=""> | 
																								<small>
																								{{company}}
																								</small>
	</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
		<ul class='navbar-nav mr-auto'>
		</ul>
    <ul class="navbar-nav float-lg-right">
			<li class="nav-item">
				<a class="nav-link" href="#">
					<i class="fa fa-user"></i>
					{{request.user}}</a>
      </li>
			&nbsp;
			<li class="nav-item">
				<a class="nav-link" href="{% url 'cadmin:logout_user' %}">
					<i class="fa fa-sign-out"></i>
					Sign Out</a>
      </li>

    </ul>

  </div>
</nav>
<div class="container-fluid">
      <div class="row">
        <nav class="col-md-2 d-none d-md-block bg-light sidebar mt-2">
          <div class="sidebar-sticky">
            <ul class="nav flex-column">
							<li class="nav-item">
								<a class="nav-link" style="border-bottom:1px dotted grey;"
																		href="{% url 'cadmin:index' %}">
									<i class="fa fa-building"></i><strong> {{company.name}}</strong>
								</a>
							</li>
              <li class="nav-item {% if url == 'profile' %} active {% endif %}">
                <a class="nav-link
								{% if url == 'profile' %}
								active
								{% endif %}
									" href="{% url 'cadmin:home' pk %}">
                  <span class="fa fa-users"></span>
                   Users<span class="sr-only">(current)</span>
                </a>
              </li>

              <li class="nav-item
							{% if url == 'divison'%}
							active
							{% endif %}
									">
									<a class="nav-link 
								{% if url == 'divison'%}
									active
									{% endif %}
									" href="{% url 'cadmin:company_divisions' pk %}">
                  <span class="fa fa-columns"></span>
									Divisions
                </a>
              </li>

              <li class="nav-item
							{% if url == 'site'%}
							active
							{% endif %}
									">
									<a class="nav-link 
									{% if url == 'site' %}
									active
									{% endif %}
									" href="{% url 'cadmin:company_sites' pk %}">
                  <span class="fa fa-sitemap"></span>
									Sites
                </a>
              </li>
              <li class="nav-item
							{% if url == 'commodity'%}
							active
							{% endif %}
									">
									<a class="nav-link 
									{% if url == 'commodity' %}
									active
									{% endif %}
									" href="{% url 'cadmin:company_commodities' pk %}">
                  <span class="fa fa-tint"></span>
									Commodities
                </a>
              </li>
              <li class="nav-item
							{% if url == 'meter'%}
							active
							{% endif %}
									">
									<a class="nav-link 
									{% if url == 'meter' %}
									active
									{% endif %}
									" href="{% url 'cadmin:company_meters' pk %}">
                  <span class="fa fa-sort-numeric-desc"></span>
									Meters
                </a>
              </li>

              <li class="nav-item
							{% if url == 'custom_field'%}
							active
							{% endif %}
									">
									<a class="nav-link 
									{% if url == 'custom_field' %}
									active
									{% endif %}
									" href="{% url 'cadmin:custom_fields' pk %}">
                  <span class="fa fa-sort-numeric-desc"></span>
									Custom Fields
                </a>
              </li>

              <li class="nav-item
							{% if url == 'master_upload'%}
							active
							{% endif %}
									">
									<a class="nav-link 
									{% if url == 'master_upload' %}
									active
									{% endif %}
									" href="{% url 'cadmin:master_upload' pk %}">
										<span class='fa fa-upload'></span>
									<strong>
									Master Upload
									</strong>
                </a>
              </li>
              <li class="nav-item
							{% if url == 'custom_field_upload'%}
							active
							{% endif %}
									">
									<a class="nav-link 
									{% if url == 'custom_field_upload' %}
									active
									{% endif %}
									" href="{% url 'cadmin:custom_field' pk %}">
										<span class='fa fa-upload'></span>
									<strong>
									Custom Upload
									</strong>
                </a>
              </li>
              <li class="nav-item
							{% if url == 'consumtion'%}
							active
							{% endif %}
									">
									<a class="nav-link 
									{% if url == 'consumtion' %}
									active
									{% endif %}
									" href="{% url 'cadmin:consumtion_data_upload' pk %}">
										<span class='fa fa-upload'></span>
									<strong>
										Consumtion Data
									</strong>
                </a>
              </li>
            </ul>
          </div>
        </nav>
			<main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
			{% block breadcrumb %}

				<div class="container-fluid mt-5">
					<div class="row">
						<div class="col-12">
							{% if messages %}
									{% for message in messages %}
											<div class="alert alert-{{ message.tags }}
												alert-dismissible fade show shadow" role="alert">
												<center>{{message}}</center>
												<button type="button" class="close" data-dismiss="alert" aria-label="Close">
													<span aria-hidden="true">&times;</span>
												</button>
											</div>
									{% endfor %}
							{% endif %}
						</div>
					</div>
					<div class="row">
						<div class="col-12">
							<nav aria-label="breadcrumb">
								{% block breadcrumbs %}
								<ol class="breadcrumb shadow">
									<li class="breadcrumb-item"><a href="{% url 'cadmin:index' %}">Home</a></li>
									{% block links %}
									{% endblock links %}
								</ol>
								{% endblock %}
							</nav>
						</div>
					</div>
				</div>
				{% endblock %}

			<div class="d-flex justify-content-between flex-wrap flex-md-nowrap
				align-items-center mt-2 pb-2 mb-3 border-bottom">
			{% block content %}
			{% endblock content %}
			</main>
			</div>
	</div>
</div>
	
<script src="{% static 'bower_components/jquery/dist/jquery.min.js' %}"></script>
<script src="{% static 'bower_components/jquery-ui/jquery-ui.min.js' %}"></script>
<script src="{% static 'bower_components/bootstrap/dist/js/bootstrap.min.js' %}"></script>
<script src="{% static 'bower_components/select2/dist/js/select2.min.js' %}"></script>
<script>
	$(".alert").delay(3000).slideUp(1000, function() {
			$(this).alert('close');
	});
</script>
{% block javascript %}
{% endblock %}
</body>
</html>