apps/cadmin/urls.py
from django.urls import path
from .views import *

app_name = 'cadmin'

urlpatterns = [
    path('', index, name='index'),
    path('logout/', logout_user, name='logout_user'),
    path('login/', login_user, name='login'),
    # company
    path('company-add',
         company_add, name='company_add'),
    path('company-edit/<int:pk>/', company_edit, name='company_edit'),

    # users
    path('company/<int:pk>/', company_home, name='home'),
    path('company/<int:pk>/account-add',
         company_user_add, name='company_user_add'),
    path('company/<int:company_pk>/account-edit/<int:pk>',
         company_user_edit, name='company_user_edit'),
    path('company/<int:company_pk>/change-password/<int:pk>',
         change_password_user, name='company_user_change_password'),
    path('company/<int:company_pk>/set-avatar/<int:pk>',
         set_user_avatar, name='set_avatar'),

    # sites
    path('company/<int:pk>/sites/',
         company_sites, name='company_sites'),
    path('company/<int:pk>/site-add/',
         company_site_add, name='company_site_add'),
    path('company/<int:company_pk>/site-edit/<int:pk>/',
         company_site_edit, name='company_site_edit'),

    # divisons
    path('company/<int:pk>/divisons/',
         company_divisions, name='company_divisions'),
    path('company/<int:pk>/divison-add/',
         company_division_add, name='company_division_add'),
    path('company/<int:company_pk>/divison-edit/<int:pk>/',
         company_divison_edit, name='company_divison_edit'),

    # commodities
    path('company/<int:pk>/commodities/',
         company_commodities, name='company_commodities'),
    path('company/<int:pk>/commodity-add/',
         company_commodity_add, name='company_commodity_add'),
    path('company/<int:company_pk>/commodity-edit/<int:pk>/',
         company_commodity_edit, name='company_commodity_edit'),

    # meters
    path('company/<int:pk>/meters/',
         company_meters, name='company_meters'),
    path('company/<int:pk>/meter-add/',
         company_meters_add, name='company_meter_add'),
    path('company/<int:company_pk>/meter-edit/<int:pk>/',
         company_meter_edit, name='company_meter_edit'),

    # fetch commodities
    path('company/<int:pk>/fetch_commodities/',
         commodity_fetch, name='fetch_commodities'),

    path('company/<int:pk>/master_upload/',
         master_upload, name='master_upload'),
    path('company/<int:pk>/custom_field/',
         custom_field_upload, name='custom_field'),

    # custom fields
    path('company/<int:pk>/custom-fields/',
         company_custom_fields, name='custom_fields'
         ),
    path('company/<int:pk>/custom-field-add/',
         company_custom_field_add, name='custom_field_add'),

    path('company/<int:pk>/consumtion_data/',
         consumtion_data_upload,
         name='consumtion_data_upload')

]

config/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi


schema_view = get_schema_view(
    openapi.Info(
        title="Enkumo API",
        default_version='v1',
        description="Enkumo Rest APIs",
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)
urlpatterns = [
    path('docs', schema_view.with_ui(
        'swagger',
        cache_timeout=0
    ), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui(
        'redoc',
        cache_timeout=0
    ), name='schema-redoc'),
    path(r'admin/', admin.site.urls),
    # Modules
    path('api/', include('apps.api.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('cadmin/', include('apps.cadmin.urls'))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/cadmin/models.py
from django.db import models

# Create your models here.

apps/sites/models.py
from datetime import datetime

from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver

from apps.commons.models import BaseModel


class Meter(BaseModel):
    number = models.CharField(max_length=100)
    commodity = models.ForeignKey(
        'data.Commodity', null=True, on_delete=models.SET_NULL)
    hh = models.BooleanField(default=False)
    site = models.ForeignKey(
        'sites.Site', null=True, blank=True,
        on_delete=models.CASCADE, related_name='meters')
    company = models.ForeignKey(
        'company.Company', null=True, blank=True,
        on_delete=models.CASCADE, related_name='meters')

    def __str__(self):
        return str(self.number)

    class Meta:
        ordering = ['-id']


class Site(BaseModel):
    name = models.CharField(max_length=256)
    street = models.CharField(max_length=255)
    city = models.CharField(max_length=100)
    postal_code = models.CharField(max_length=100)
    company = models.ForeignKey(
        'company.Company', null=True, on_delete=models.SET_NULL)
    country = models.ForeignKey(
        'region.Country', null=True, on_delete=models.SET_NULL)
    division = models.ForeignKey(
        'company.Devision', null=True, on_delete=models.SET_NULL)
    supplier = models.CharField(max_length=125, null=True, blank=True)
    dno = models.CharField(max_length=125, null=True, blank=True)
    legal_entity_name = models.CharField(max_length=125, null=True, blank=True)

    class Meta:
        ordering = ['-id']

    def __str__(self):
        return str(self.name)


@receiver(post_save, sender=Site)
def save_commodities(sender, instance, **kwargs):
    from apps.data.models import Commodity
    commodities = ['Gas', 'Power']
    for commodity in commodities:
        commodity, _ = Commodity.objects.get_or_create(
            name=commodity,
            site=instance,
            company=instance.company
        )

apps/cadmin/views/commodities.py
from django.contrib import messages
from django.contrib.auth import get_user_model, logout
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.shortcuts import redirect, render

from apps.company.models import Company, Devision, Profile
from apps.sites.models import Site
from apps.data.models import Commodity

from ..forms import *


@login_required
def company_commodities(request, pk):
    context = {}
    try:
        company = Company.objects.get(pk=pk)
    except Company.DoesNotExist:
        messages.info(request, "No company found")
        return redirect("cadmin:index")
    commodities = Commodity.objects.filter(site__company=company)
    sites = Site.objects.filter(company=company)

    if request.GET.get('site'):
        query = request.GET.get('site')
        site = Site.objects.get(pk=int(query))
        context['query'] = query
        context['site'] = site
        commodities = commodities.filter(site__pk=int(query))
    else:
        first_site = sites.first()
        context['first_site'] = first_site
        commodities = commodities.filter(site=first_site)

    context['sites'] = sites
    context['pk'] = pk
    context['url'] = 'commodity'
    context['objects'] = commodities
    context['company'] = company
    return render(request, 'cadmin/commodities/commodities.html', context)


@transaction.atomic
@login_required
def company_commodity_add(request, pk):
    context = {}
    try:
        company = Company.objects.get(pk=pk)
    except Company.DoesNotExist:
        messages.info(request, "No company found")
        return redirect("cadmin:index")

    form = CommodityForm(request.POST or None)
    form.fields['site'].queryset = Site.objects.filter(company=company)
    if request.method == 'POST':
        if form.is_valid():
            instance = form.save()
            instance.company = company
            instance.save()
            messages.success(request, 'Commodity Added Successfully.')
            return redirect('cadmin:company_commodities', pk)

    context['pk'] = pk
    context['url'] = 'commodity'
    context['form'] = form
    context['company'] = company

    return render(request, 'cadmin/commodities/commoditiy_add.html', context)


@transaction.atomic
@login_required
def company_commodity_edit(request, company_pk, pk):
    context = {}

    try:
        company = Company.objects.get(pk=company_pk)
    except Company.DoesNotExist:
        messages.info(request, "No company found")
        return redirect("cadmin:index")

    try:
        commodity = Commodity.objects.get(pk=pk)
    except Commodity.DoesNotExist:
        messages.info(request, "No commodity found")
        return redirect("cadmin:company_commodities", company_pk)

    form = CommodityEditForm(request.POST or None, instance=commodity or None)
    if request.method == 'POST':
        if form.is_valid():
            instance = form.save()
            instance.site = commodity.site
            instance.company = company
            instance.save()
            messages.success(
                request, 'Commodity {} Edited Successfully.'.format(commodity.name))
            return redirect('cadmin:company_commodities', company_pk)

    context['pk'] = company_pk
    context['form'] = form
    context['commodity'] = commodity
    context['url'] = 'commodity'
    context['company'] = Company.objects.get(pk=company_pk)

    return render(request, 'cadmin/commodities/commodity_edit.html', context)

apps/cadmin/views/company.py
from django.contrib import messages
from django.contrib.auth import authenticate, get_user_model, login
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.shortcuts import redirect, render


from apps.company.models import Company, Profile
from apps.sites.models import Site

from ..forms import *

# Create your views here.
User = get_user_model()


@login_required
def index(request):
    companies = Company.objects.all().order_by("-id")
    context = {"objects": companies}
    return render(request, 'cadmin/index.html', context)


@transaction.atomic
@login_required
def company_add(request):
    context = {}
    form = CompanyForm(request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            messages.success(request, 'Company Added Successfully.')
            return redirect('cadmin:index')

    context['form'] = form

    return render(request, 'cadmin/company_add.html', context)


@transaction.atomic
@login_required
def company_edit(request, pk):
    context = {}
    try:
        company = Company.objects.get(pk=pk)
    except Company.DoesNotExist:
        messages.error(request, "Company Not Found")
        return redirect('cadmin:index')

    form = CompanyForm(request.POST or None, instance=company)
    if request.method == 'POST':
        if form.is_valid():
            if form.has_changed():
                form.save()
                messages.success(request, 'Company Edited Successfully.')
            return redirect('cadmin:index')

    context['form'] = form
    context['company'] = company

    return render(request, 'cadmin/company_edit.html', context)


@login_required
def company_home(request, pk):
    context = {}
    try:
        company = Company.objects.get(pk=pk)
    except Company.DoesNotExist:
        messages.info(request, "No company found")
        return redirect("cadmin:index")
    profiles = Profile.objects.filter(company=company).order_by('-id')

    context['company'] = company
    context['profiles'] = profiles
    context['url'] = 'profile'
    context['pk'] = pk
    return render(request, 'cadmin/company_home.html', context)


@transaction.atomic
@login_required
def company_user_add(request, pk):
    context = {}
    try:
        company = Company.objects.get(pk=pk)
    except Company.DoesNotExist:
        messages.info(request, "No company found")
        return redirect("cadmin:index")
    form = UserRegisterForm(request.POST or None)
    form.fields['site'].queryset = company.site_set.all()
    if request.method == 'POST':
        if form.is_valid():
            user = form.save()
            role = form.cleaned_data.get('role')
            site = form.cleaned_data.get('site')
            phone_number = form.cleaned_data.get('phone_number')
            Profile.objects.create(
                company=company,
                user=user,
                role=role,
                site=site,
                phone_number=phone_number
            )
            messages.success(request, 'User Added Successfully.')
            return redirect('cadmin:home', pk)

    context['pk'] = pk
    context['form'] = form
    context['url'] = 'profile'
    context['company'] = company

    return render(request, 'cadmin/accounts/account_create.html', context)


@transaction.atomic
@login_required
def company_user_edit(request, company_pk, pk):
    context = {}
    try:
        user = User.objects.get(pk=pk)
    except User.DoesNotExist:
        messages.info(request, "No user found")
        return redirect('cadmin:company_home', company_pk)
    try:
        company = Company.objects.get(pk=company_pk)
    except Company.DoesNotExist:
        messages.info(request, "No company found")
        return redirect('cadmin:index')

    form = UserEditForm(request.POST or None, instance=user or None)
    profile_form = ProfileEditForm(
        request.POST or None, request.FILES or None,
        instance=user.profile
    )
    profile_form.fields['site'].queryset = company.site_set.all()

    if request.method == 'POST':
        if form.is_valid() and profile_form.is_valid():
            if form.has_changed():
                user = form.save()
            if profile_form.has_changed():
                profile_form.save()
            messages.success(
                request, f'User {user.email} Edited Successfully.')
            return redirect('cadmin:home', company_pk)

    context['pk'] = company_pk
    context['form'] = form
    context['profile_form'] = profile_form
    context['url'] = 'profile'
    context['user'] = user
    context['company'] = company

    return render(request, 'cadmin/accounts/accounts_edit.html', context)


@transaction.atomic
@login_required
def change_password_user(request, company_pk, pk):
    context = {}
    try:
        user = User.objects.get(pk=pk)
    except User.DoesNotExist:
        messages.info(request, "No user found")
        return redirect('cadmin:company_home', company_pk)

    form = ChangePasswordForm(request.POST or None, instance=user)

    if request.method == 'POST':
        if form.is_valid():
            if form.has_changed():
                form.save()
                messages.success(
                    request, f'Password changed for {user.email} .')
            return redirect('cadmin:home', company_pk)

    context['pk'] = company_pk
    context['form'] = form
    context['url'] = 'profile'
    context['user'] = user
    context['company'] = Company.objects.get(pk=company_pk)

    return render(request, 'cadmin/accounts/change_password.html', context)


@transaction.atomic
@login_required
def set_user_avatar(request, company_pk, pk):
    context = {}
    try:
        user = User.objects.get(pk=pk)
    except User.DoesNotExist:
        messages.info(request, "No user found")
        return redirect('cadmin:company_home', company_pk)
    try:
        profile = user.profile
    except Profile.DoesNotExist:
        messages.info(request, "User profile does not exists")
        return redirect('cadmin:company_home', company_pk)

    form = ProfileAvatarForm(
        request.POST or None,
        request.FILES,
        instance=profile
    )

    if request.method == 'POST':
        if form.is_valid():
            if form.has_changed():
                form.save()
                messages.success(
                    request, f'Avatar set for {user.email} .')
            return redirect('cadmin:home', company_pk)

    context['pk'] = company_pk
    context['form'] = form
    context['url'] = 'profile'
    context['user'] = user
    context['profile'] = profile
    context['company'] = Company.objects.get(pk=company_pk)

    return render(request, 'cadmin/accounts/set_avatar.html', context)


def login_user(request):
    if request.user.is_authenticated:
        return redirect("cadmin:index")
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)

        if user is None:
            messages.warning(request, "Invalid login credentials")
            return redirect(request.path)

        if not user.is_superuser or not user.is_staff:
            messages.info(request, "Not authorized")
            return redirect(request.path)

        if user.is_active:
            login(request, user)
            return redirect("cadmin:index")

    return render(request, 'cadmin/login_user.html')

apps/cadmin/templates/cadmin/sites/site_create.html
{% extends 'sidebar.html' %}
{% load crispy_forms_tags %}
{% block title %} Site Create{% endblock %}

{% block links %}
<li class="breadcrumb-item"> <a href="{% url 'cadmin:company_sites' company.pk %}">Sites</a> </li>
<li class="breadcrumb-item active">Sites Create</li>
{% endblock links %}

{% block content %}
<div class="container-fluid">
	<div class="row">
		<div class="col-12">
			<div class="card shadow">
				<div class="card-body">
					<h5 class="card-title">Add Site</h5>
					<hr>

					<div class="">
						<form method="POST">
							{% csrf_token %}

							<div class="form-row col-md-12">
									<div class="form-group col-md-6">
												{{form.name|as_crispy_field}}
									</div>
									<div class="form-group col-md-6">
												{{form.street|as_crispy_field}}
									</div>
									<div class="form-group col-md-6">
												{{form.city|as_crispy_field}}
									</div>
									<div class="form-group col-md-6">
												{{form.postal_code|as_crispy_field}}
									</div>
									<div class="form-group col-md-6">
												{{form.country|as_crispy_field}}
									</div>
									<div class="form-group col-md-6">
												{{form.division|as_crispy_field}}
									</div>
									<div class="form-group col-md-6">
												{{form.supplier|as_crispy_field}}
									</div>
									<div class="form-group col-md-6">
												{{form.dno|as_crispy_field}}
									</div>
									<div class="form-group col-md-12">
												{{form.legal_entity_name|as_crispy_field}}
									</div>
							</div>
							<div class="">
									<h5>Custom Fields</h5>
									<hr>
									
									<div id="id_custom_fields">
									</div>
							</div>

							<div class="form-group col-12">
									<button class="btn btn-outline-secondary" type="submit">Submit</button>
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
	{% endblock content %}
	{% block javascript %}
	<script>

			$("select").select2({
				theme: 'bootstrap',
				dropdownAutoWidth: true,
				width: 'auto'
			});

$("#id_country").change(function(){
	$("#id_custom_fields").empty();

	let country_id = $(this).val();
	let company_id = {{company.pk}};

	let uri  = "/api/account/get-custom-fields/?company="+ company_id + "&country=" + country_id
	$.ajax({
    type: "GET",
		url : uri,
		success : function(data){
			$.each(data, function(key, value){
				console.log(value);
				let field_type = value.field_type
				let name = value.name
				let input = "<div class='form-group col-12'> <div id='div_id_" + name + " 'class='form-group'> <label for='id_" + name +
					"' class='requiredField'>"+ name+"<span class='asteriskField'>*</span> </label> <div class=''><input type="+ field_type +" name='" +name+"' maxlength='100' class='"+field_type +"input form-control' required='' id='id_" + name+ "'> </div> </div> </div>"
				$("#id_custom_fields").append(input);
			})
		}

	});


})


	</script>

	{% endblock javascript %}

apps/cadmin/templates/cadmin/sites/site_edit.html
{% extends 'sidebar.html' %}
{% load crispy_forms_tags %}
{% block title %} Edit Site{% endblock %}
{% block links %}
<li class="breadcrumb-item"> <a href="{% url 'cadmin:company_sites' company.pk %}">Sites</a> </li>
<li class="breadcrumb-item active">Sites Edit</li>
{% endblock links %}

{% block content %}
<div class="container-fluid">
	<div class="row">
		<div class="col-12">
			<div class="card shadow">
				<div class="card-body">
					<h5 class="card-title">Edit Site {{site.name}}</h5>
					<hr>
					<div class="">
						<form method="POST">
							{% csrf_token %}

							<div class="form-row col-md-12">
									<div class="form-group col-md-6">
												{{form.name|as_crispy_field}}
									</div>
									<div class="form-group col-md-6">
												{{form.street|as_crispy_field}}
									</div>
									<div class="form-group col-md-6">
												{{form.city|as_crispy_field}}
									</div>
									<div class="form-group col-md-6">
												{{form.postal_code|as_crispy_field}}
									</div>
									<div class="form-group col-md-6">
												{{form.division|as_crispy_field}}
									</div>
									<div class="form-group col-md-6">
												{{form.supplier|as_crispy_field}}
									</div>
									<div class="form-group col-md-6">
												{{form.dno|as_crispy_field}}
									</div>
									<div class="form-group col-md-6">
												{{form.legal_entity_name|as_crispy_field}}
									</div>
							</div>

									<div class="custom_fields">
										<div class="row">
											<div class="col-12">
										<h5>Custom Fields</h5>
										<hr>

										<div class="form-row col-12">
									{% for val in custom_field_values %}
									<div class="form-group col-md-6" id="div_id_{{val.field.name}}">
										<label class="" for="id_legal_entity_name">{{val.field.name}} 
											<span class="asteriskField">*</span>
										</label>
									<div class="">
										<input class="{{val.field.field_type}}input
										{{val.field.fieldfield_type}}Input form-control" 
										id="id_{{val.field.name}}" 
										{% if val.field.field_type == 'text' %} maxlength="125" {% endif %} 
										name="{{val.field.name}}" type="text" value="{{val.value}}"
										required>
									</div>
								</div>

									{% endfor %}
							</div>
											</div>
										</div>
									</div>
							<div class="form-group col-12">
									<button class="btn btn-outline-secondary" type="submit">Submit</button>
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
	{% endblock content %}
	{% block javascript %}
	<script>
			$("select").select2({
				theme: 'bootstrap',
				dropdownAutoWidth: true,
				width: 'auto'
			});


	</script>

	{% endblock javascript %}

apps/cadmin/templates/cadmin/sites/sites.html
{% extends 'sidebar.html' %}
{% block title %} Sites{% endblock %}

{% block links %}
<li class="breadcrumb-item active">Sites</li>
{% endblock links %}

{% block content %}

<div class="container-fluid">
	<div class="row">
		<div class="col-12">

			<div class="card shadow">
				<div class="card-body">
					<div class="div-wrapper mb-3">
							<div class="row no-gutters">
								<div class="col-6">
									<h5 class="card-title">Sites</h5>
									</div>
									<div class="col-6">
										<a href="{% url 'cadmin:company_site_add' pk %}" class="btn
											btn-outline-secondary pull-right">Create New</a>
									</div>
								</div>
							</div>
					<table class="table">
						<thead>
							<tr>
								<th scope="col">#</th>
								<th scope="col">Name</th>
								<th scope="col">City</th>
								<th scope="col">Street</th>
								<th scope="col">Postal Code</th>
								<th scope="col">Country</th>
								<th scope="col">Division</th>
								<th scope="col">Supplier</th>
								<th scope="col">DNO</th>
								<th scope="col">Legal Entity Name</th>
								<th scope="col">Actions</th>
							</tr>
						</thead>
						<tbody>
							{% for object in objects %}
							<tr>
								<th scope="row">{{forloop.counter}}</th>
								<td>{{object.name}}</td>
								<td>{{object.city}}</td>
								<td>{{object.street}}</td>
								<td>{{object.postal_code}}</td>
								<td>{{object.country}}</td>
								<td>{{object.division}}</td>
								<td>{{object.supplier}}</td>
								<td>{{object.dno}}</td>
								<td>{{object.legal_entity_name}}</td>
								<td>
									<a class="btn btn-outline-secondary" href="{% url 'cadmin:company_site_edit' pk object.pk %}"> Edit</a>
								</td>
							</tr>
							{% empty %}
							<tr>
								<td colspan="3">
							No sites yet
								</td>
							</tr>
							{% endfor %}
						</tbody>
					</table>

				</div>
			</div>
		</div>
	</div>
</div>
{% endblock content %}